menu:
  首页: /
  web开发: /webdevelop
  移动开发: /mobiledevelop
  nodejs: /nodejsdevelop
  项目: /mycase
  杂谈: /mylife
  关于我: /aboutme

widgets:
- category
- about_me
- tag
- recent_posts
- links

excerpt_link: 阅读全文

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

links:
- name: 树莓派的奇幻漂流
  link: http://www.codeforfun.info/

about_me:
  title: 关于我
  pic: /images/girl.jpg
  name: dancing-waves
  texts:
  - 专注前端领域，但是不仅专注前端
  - 熟悉html/html5、css2/css3、javascript、jquery、coffeescript、nodejs

comment_provider: facebook
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light